### ISSUE TITLE
Receivers lying in the same plane.

### ISSUE THREAD

**Issue by akjain90** [StevenJL/tdoa_localization#3]
Hi,
I would like to ask, what will happen if all the receivers lie in the same plane?
For example I have 5 receivers all are embedded in the roof of a room and one sender on the floor of the room , then I can assume that the Z coordinate (or either of the three coordinates) of all the receivers will be same (or zero). In that case the coefficient matrix that I will get will have last column of complete zeros. Any idea how to deal with this issue?

Thanks

**Comment by StevenJL** [comment]
Hi @akjain90, as you pointed out the coefficient matrix would have a column of zeroes.  iirc how the rank-nullity theorem works (https://en.wikipedia.org/wiki/Rank%E2%80%93nullity_theorem), the rank in this case would be 2, since one of the columns would be zeros, n = 3 since there are 3 columns.  The nullity of the matrix should be 3 - 1, meaning the solution would be a line, rather than a point.  However, since you say the sender is on the floor (a plane), may I suggest you find the intersection of this line and the plane to locate the source?

Another approach would be to simply vary the height of your receivers slightly if possible, so they are not all on the same plane.

**Comment by akjain90** [comment]
Thank you,
I will work on your advice. Even i am planning to change the height of the receivers.
